Patient
rublin/my-doctor-bot pull request #1
Opened 2020-09-22 18:57 UTC by OlenkaSheremet

2020-09-23 09:20 UTC, rublin requested changes
@OlenkaSheremet Good work, I really proud of you. Please fix these small comments and I'm going to approve the PR

2020-09-23 09:20 UTC, rublin commented on pom.xml
Please remove empty extra lines. It is not your fault, but I'd like to merge clean code

2020-09-23 09:20 UTC, rublin commented on src/main/java/com/mydoctor/mydoctorbot/model/Patient.java
> +    @GeneratedValue(strategy= GenerationType.IDENTITY)
it looks like you forgot to add a space before the equals symbol. It is a good practice to run code format before commit changes (ctrl + alt + shift + L in idea)

2020-09-23 09:20 UTC, rublin commented on src/main/java/com/mydoctor/mydoctorbot/model/Patient.java
> +    private String typeOfDoctor;
We don't need typeOfDoctor inside the patient. We will store relations between the patient and the doctor in another table.

2020-09-23 09:20 UTC, rublin commented on src/main/java/com/mydoctor/mydoctorbot/service/PatientService.java
> +
Please remove this empty line

2020-09-23 09:20 UTC, rublin commented on src/main/resources/db/migration/V2__create_patient_table.sql
> +	first_name varchar not null,
for the doctor, we need the full name and they are required fields. but for the patient, we shouldn't take name and surname as required fields. so, my suggestion is not to mark them as required (not null).

2020-09-29 18:00 UTC, OlenkaSheremet commented on pom.xml
done

2020-09-30 15:46 UTC, rublin approved these changes

2020-09-30 18:23 UTC, aliska2 approved these changes
approve

2020-10-07 16:43 UTC, merged